### ISSUE TITLE
Minimum Karma

### ISSUE THREAD

**Issue by Foggalong** [unixporn/upmo#31]
Reddit has had an influx of spam submission recently for links to porn sites. This isn't related the subs name funnily enough because other sfw-titled subs are having the exact same problem. The majority of the link posts get removed by the bot for being tagged incorrectly, but almost all of the self posts are getting through.

One proposed solution to combat this has been a minimum karma for posters, which would work something like this:
1. Bot checks the posters karma
2. If karma < 5, post is removed
3. Post is reported so that a real mod can double check
4. Bot leaves a comment saying it's been caught in spam filter, human mod will check asap
5. Human mod verifies whether the post was removed correctly

**Comment by Kornhe** [comment]
I tried to add it in commit ce9454f on branch karma, never did python so not sure if this is working

**Comment by Foggalong** [comment]
The general format looks correct, but there're a few syntax problems which will cause it to crash. I can either fix them myself or point those out with review comments so you can address them. I don't mind which? :)

**Comment by Kornhe** [comment]
Please point them, I'd like to know where I did wrong :D

**Comment by Foggalong** [comment]
[Done](https://github.com/unixporn/upmo/commit/ce9454fd0a6d5213a08b84b1e0667c1d067a62be) :+1:

**Comment by Kornhe** [comment]
@Foggalong it should be better now, I think I fixed the indentation and added the blank lines that I removed, sorry about that 😛

**Comment by Foggalong** [comment]
No worries! Not at a computer where I can test the functionality right now but will do so asap

**Comment by Kornhe** [comment]
Awesome, keep me informed 😄
