### ISSUE TITLE
Upmo does not report a post after removing it

### ISSUE THREAD

**Issue by Kornhe** [unixporn/upmo#39]
For instance, when removing a post if OP does not meet karma requirements, it won't report it since it is removed.

**Comment by Foggalong** [comment]
Oh no, that's not good. Will see what's going on with this today :confused:

**Comment by Foggalong** [comment]
I meant to follow up on this: I did a lot of playing around and as far as I can tell and with all my testing this worked, it just doesn't seem to be working when in the full bot. If anyone has any ideas why this isn't working let me know.

**Comment by Kornhe** [comment]
Isn't there something like a way to completely ignore approved posts ?

**Comment by Foggalong** [comment]
I'm not familiar enough with praw to know if there's a way to fetch that data - the way the bot knows whether it's approved a post is by referencing its own logs, but obviously human mods can't add to that :confused:

**Comment by Kornhe** [comment]
Closing since it will (should) now send a message to the subreddit instead of reporting the post.

**Comment by Foggalong** [comment]
Don't close the issue until the fix has been merged, tested, and deployed to the server. I'll do this asap, but currently inhibited by a broken wrist

**Comment by Kornhe** [comment]
Oh shit, I'm sorry :x
